directory: ~/Dropbox/Media/Music
library: ~/Dropbox/Media/Music/beet-library.db
plugins: convert alternatives copyartifacts
convert:
  copy_album_art: yes
  never_convert_lossy_files: yes
  formats:
    cd:
      command: ffmpeg -i $source -y -vn -sample_fmt s16 -ar 44100 $dest
      extension: flac
    mobile:
      command: ffmpeg -i $source -y -vn -ab 320k -ar 44100 $dest
      extension: mp3
alternatives:
  cloudplayer:
    directory: ../../Apps/CloudPlayer
    formats: mobile AAC aac mp3
    query: ""
    removable: true
copyartifacts:
    extensions: .pdf .jpg .png
    print_ignored: yes
