directory: ~/Dropbox/Media/Music
library: ~/Dropbox/Media/Music/beet-library.db
plugins: convert copyartifacts
convert:
  copy_album_art: yes
  never_convert_lossy_files: yes
  formats:
    cd:
      command: ffmpeg -i $source -y -vn -sample_fmt s16 -ar 44100 $dest
      extension: flac
copyartifacts:
    extensions: .pdf .jpg .png
    print_ignored: yes
