directory: /home/beets/music
library: /home/beets/music/beet-library.db
plugins: convert extrafiles
convert:
  copy_album_art: yes
  never_convert_lossy_files: yes
  formats:
    cd:
      command: ffmpeg -i $source -y -vn -sample_fmt s16 -ar 44100 $dest
      extension: flac
    cd_with_dither:
      command: ffmpeg -i $source -y -vn -sample_fmt s16 -ar 44100 -dither_method triangular $dest
      extension: flac
extrafiles:
    patterns:
        jpg: '*.jpg'
        pdf: '*.pdf'
        png: '*.png'

