tap "homebrew/bundle"
tap "homebrew/cask"

brew "circleci"
brew "git-lfs"

cask "slack"
cask "android-studio"
cask "libreoffice" # for creating/editing XLSForms
cask "google-cloud-sdk"
cask "imageoptim" # for optimizing screenshots
