tap "homebrew/bundle"

brew "circleci"
brew "git-lfs"
brew "gh"
brew "gradle-completion"

cask "slack"
cask "android-studio"
cask "google-cloud-sdk"
cask "imageoptim" # for optimizing screenshots
cask "intellij-idea-ce"
