brew "circleci"
brew "git-lfs"
brew "gh"
brew "gradle-completion"
brew "base64"
brew "qpdf"
brew "zbar"

cask "slack"
cask "android-studio"
cask "google-cloud-sdk"
cask "imageoptim" # for optimizing screenshots
cask "intellij-idea-ce"
